on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
    inputs:
      make_release:
        type: boolean
        required: true

jobs:
  build:
    runs-on: windows-2025-vs2026
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
    - run: cmake -Bbuild -DCMAKE_BUILD_TYPE=Release .
    - run: cmake --build build --config Release
    - run: |
        mkdir dest
        cp build/*.exe build/*.dll ./dest/
        cp README.md ./dest/
        mkdir dest/Acknowledgements
        cp ./third_party/minhook/LICENSE.txt dest/Acknowledgements/minhook.txt
        pushd dest
        zip -r -9 ../NotOnArm64.zip .
      shell: bash
    - uses: actions/upload-artifact@v7
      with:
        name: NotOnArm64
        path: NotOnArm64.zip